---
apiVersion: v1
kind: Namespace
metadata:
  name: zigbee2mqtt
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: zigbee2mqtt-kustomize
  namespace: flux-system
spec:
  interval: 1h
  url: https://github.com/dawg-io/zigbee2mqtt-kustomize
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: zigbee2mqtt
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: zigbee2mqtt-kustomize
  path: "./"
  prune: true
  wait: true
  timeout: 5m
  dependsOn:
    - name: infrastructure-configs
