---
apiVersion: v1
kind: Namespace
metadata:
  name: mealie
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: mealie-kustomize
  namespace: flux-system
spec:
  interval: 1h
  url: https://github.com/turbo5000c/mealie-kustomize
  ref:
    branch: main  # no git tags yet on this repo
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mealie
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: mealie-kustomize
  path: "./"
  prune: true
  wait: true
  timeout: 5m
  dependsOn:
    - name: infrastructure-configs
