---
apiVersion: v1
kind: Namespace
metadata:
  name: code-server
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: nicholaswilde
  namespace: flux-system
spec:
  interval: 24h
  url: https://nicholaswilde.github.io/helm-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: code-server
  namespace: code-server
spec:
  interval: 30m
  chart:
    spec:
      chart: code-server
      version: "2.x"
      sourceRef:
        kind: HelmRepository
        name: nicholaswilde
        namespace: flux-system
      interval: 12h
  values:
    ingress:
      enabled: true
      ingressClassName: traefik
      hosts:
        - host: code.local.example.com
          paths:
            - path: /
              pathType: Prefix
    # Add your values here
    # See chart documentation for available values
