apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager.yaml
  - metallb.yaml
  - sealed-secrets.yaml
  - ceph-csi-rbd.yaml
  - ceph-csi-cephfs.yaml
  - csi-snapshotter.yaml
